export const MATH_PUZZLE_LEVELS = [
  {
    id: 0,
    rows: 1,
    columns: 1,
    addition: true,
    subtraction: false,
    multiplication: false,
    division: false,
    name: "Level 1",
  },
  {
    id: 1,
    rows: 2,
    columns: 1,
    addition: true,
    subtraction: false,
    multiplication: false,
    division: false,
    name: "Level 2",
  },
  {
    id: 2,
    rows: 2,
    columns: 2,
    addition: true,
    subtraction: false,
    multiplication: false,
    division: false,
    name: "Level 3",
  },
  {
    id: 3,
    rows: 2,
    columns: 2,
    addition: true,
    subtraction: true,
    multiplication: false,
    division: false,
    name: "Level 4",
  },
  {
    id: 4,
    rows: 3,
    columns: 3,
    addition: true,
    subtraction: true,
    multiplication: false,
    division: false,
    name: "Level 5",
  },
  {
    id: 5,
    rows: 3,
    columns: 3,
    addition: true,
    subtraction: true,
    multiplication: true,
    division: false,
    name: "Level 6",
  },
  {
    id: 6,
    rows: 4,
    columns: 4,
    addition: true,
    subtraction: true,
    multiplication: true,
    division: true,
    name: "Level 7",
  },
];
